### ISSUE TITLE
gnmi example is not working

### ISSUE THREAD

**Issue by ihrasko** [PANTHEONtech/lighty#1632]
## Bug Description:
The issue is traced back to a misconfiguration in the provided simulator_config.json file, specifically involving the incorrect version of iana-if-type. This causes the lighty-gnmi-simulator to fail during the initialization process.

## Affected Branches:
- lighty.io 19.0.0 
- Main branch

## Steps to Reproduce:
1. Clone the repository:
``` 
git clone git@github.com:PANTHEONtech/lighty.git 
cd lighty 
```
2. Build the project:
```
mvn clean install
```
3. Navigate to the relevant example:
```
cd lighty-examples/lighty-gnmi-community-restconf-app
```
4. Unzip the simulator binary:
```
unzip ../../lighty-modules/lighty-gnmi/lighty-gnmi-device-simulator/target/lighty-gnmi-device-simulator-20.0.0-SNAPSHOT-bin.zip
```
5. Run the simulator:
```
java -jar lighty-gnmi-device-simulator-20.0.0-SNAPSHOT/lighty-gnmi-device-simulator-20.0.0-SNAPSHOT.jar -c simulator/simulator_config.json
```

## Error Encountered:
The execution will terminate with the following error:
```
ERROR [main] (GnmiSimulatorApp.java:54) - Lighty gNMI application - failed during creating schema context:
io.lighty.modules.gnmi.simulatordevice.utils.EffectiveModelContextBuilder$EffectiveModelContextBuilderException: Provided list of YangModuleInfo  is empty
at io.lighty.modules.gnmi.simulatordevice.utils.EffectiveModelContextBuilder.addYangModulesInfo(EffectiveModelContextBuilder.java:68) ~[lighty-gnmi-device-simulator-20.0.0-SNAPSHOT.jar:?]
at io.lighty.modules.gnmi.simulatordevice.impl.SimulatedGnmiDevice.start(SimulatedGnmiDevice.java:129) ~[lighty-gnmi-device-simulator-20.0.0-SNAPSHOT.jar:?]
at io.lighty.modules.gnmi.simulatordevice.main.GnmiSimulatorApp.start(GnmiSimulatorApp.java:51) [lighty-gnmi-device-simulator-20.0.0-SNAPSHOT.jar:?]
at io.lighty.modules.gnmi.simulatordevice.main.GnmiSimulatorApp.main(GnmiSimulatorApp.java:30) [lighty-gnmi-device-simulator-20.0.0-SNAPSHOT.jar:?]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.grpc.Server.isShutdown()" because "this.server" is null
at io.lighty.modules.gnmi.simulatordevice.impl.SimulatedGnmiDevice.stop(SimulatedGnmiDevice.java:163)
at io.lighty.modules.gnmi.simulatordevice.main.GnmiSimulatorApp.shutdown(GnmiSimulatorApp.java:67)
at io.lighty.modules.gnmi.simulatordevice.main.GnmiSimulatorApp.start(GnmiSimulatorApp.java:55)
at io.lighty.modules.gnmi.simulatordevice.main.GnmiSimulatorApp.main(GnmiSimulatorApp.java:30)
```

## Environment:

- OS: Ubuntu 22.04.2
- Java Version 20.0.1
- Maven version 3.9.2

## Additional Notes:
It is crucial update the configuration file (simulator_config.json) to ensure the correct version of iana-if-type is specified, resolving the issue during startup.

**Comment by ihrasko** [comment]
Fixed in https://github.com/PANTHEONtech/lighty/pull/1625 (main) and https://github.com/PANTHEONtech/lighty/pull/1631 (19.x). The fix will be available in lighty.io 19.1.0.
