### ISSUE TITLE
lighty-community-aaa-restconf-app start fails with exception 

### ISSUE THREAD

**Issue by jveverka** [PANTHEONtech/lighty#171]
when started, lighty-examples/lighty-community-aaa-restconf-app fails with exception 

INFO [main] (AbstractLightyModule.java:113) - Submitted start of LightyModule AAALighty.
Exception in thread "pool-12-thread-1" java.lang.RuntimeException: java.lang.RuntimeException: javassist.NotFoundException: getInstance(..) is not found in org.opendaylight.aaa.AAAShiroProvider
        at io.lighty.kit.examples.community.aaa.restconf.Main$1.onFailure(Main.java:131)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: javassist.NotFoundException: getInstance(..) is not found in org.opendaylight.aaa.AAAShiroProvider
        at io.lighty.aaa.AAALightyShiroProvider.injectLightyShiroProviderMethodsToOriginalProvider(AAALightyShiroProvider.java:296)
        at io.lighty.aaa.AAALightyShiroProvider.<init>(AAALightyShiroProvider.java:91)
        at io.lighty.aaa.AAALightyShiroProvider.newInstance(AAALightyShiroProvider.java:158)
        at io.lighty.aaa.AAALighty.initProcedure(AAALighty.java:68)
        at io.lighty.core.controller.api.AbstractLightyModule.lambda$start$0(AbstractLightyModule.java:117)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        ... 3 more
Caused by: javassist.NotFoundException: getInstance(..) is not found in org.opendaylight.aaa.AAAShiroProvider
        at javassist.CtClassType.getDeclaredMethod(CtClassType.java:1343)
        at io.lighty.aaa.AAALightyShiroProvider.injectLightyShiroProviderMethodsToOriginalProvider(AAALightyShiroProvider.java:242)
        ... 10 more

**Comment by vainyksi** [comment]
Closing as this was fixed in upstream for version 13.1.0
