### ISSUE TITLE
Lighty spring-boot netconf application 

### ISSUE THREAD

**Issue by Prajwal-Patil31** [PANTHEONtech/lighty#1791]
**Describe the bug**
I am using lighty spring- boot application to add Netconf devices and to perform basic Netconf operations through the Spring Boot code. But the issue is whenever I am trying to add some devices other than the Toster device the status I get is connecting but when I am trying to connect to the Toster device the status is connected. How to resolve this issue. I want to connect to any Netconf device through this code how to perform it. 

**Branch**
lighty.io branch [15.1.0]

**To Reproduce**
1. git checkout https://...
2. cd lighty
3. mvn clean install

**Expected behavior**

**Screenshots**
Added

**Environment (please complete the following information):**
 - OS: linux
 - Java Version 11
![TosterStatus](https://github.com/PANTHEONtech/lighty/assets/124030586/c18b9299-176a-4f0a-8e08-50d9a45560c8)
![TosterDevice](https://github.com/PANTHEONtech/lighty/assets/124030586/faea99f6-c504-4dc3-8fab-1860b041a220)
![StimulatorDevice](https://github.com/PANTHEONtech/lighty/assets/124030586/3cba67b1-a7e4-46aa-b637-f65ece58d7e8)
![RestConfSpring-boot](https://github.com/PANTHEONtech/lighty/assets/124030586/69d61dd9-0d32-42fc-bd8e-acabbb07461f)
![Login](https://github.com/PANTHEONtech/lighty/assets/124030586/c730764e-d8f9-4797-b505-34e294ffeefc)

 - Maven version 3.9.5

**Additional context**
log output

> 2024-03-14 15:39:39.106  WARN 136285 --- [ntLoopGroup-3-7] io.netty.bootstrap.Bootstrap             : Unknown channel option 'SO_BACKLOG' for channel '[id: 0x088ab75c]'
> 2024-03-14 15:39:39.109  INFO 136285 --- [ntLoopGroup-7-7] io.netty.handler.logging.LoggingHandler  : [id: 0x088ab75c] REGISTERED
> 2024-03-14 15:39:39.109  INFO 136285 --- [ntLoopGroup-7-7] io.netty.handler.logging.LoggingHandler  : [id: 0x088ab75c] CONNECT: /127.0.0.1:17830
> 2024-03-14 15:39:39.113  INFO 136285 --- [ntLoopGroup-7-7] io.netty.handler.logging.LoggingHandler  : [id: 0x088ab75c] CLOSE
> 2024-03-14 15:39:39.114  INFO 136285 --- [ntLoopGroup-7-7] io.netty.handler.logging.LoggingHandler  : [id: 0x088ab75c] UNREGISTERED
> 2024-03-14 15:40:01.897  WARN 136285 --- [ntLoopGroup-3-8] io.netty.channel.ChannelInitializer      : Failed to initialize a channel. Closing: [id: 0xdffa34d2]
> 
> io.netty.channel.ChannelPipelineException: org.opendaylight.netconf.nettyutil.ReconnectPromise$1 is not a @Sharable handler, so can't be added or removed multiple times.
>         at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600) ~[netty-transport-4.1.69.Final.jar!/:4.1.69.Final]
>         at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202) ~[netty-transport-4.1.69.Final.jar!/:4.1.69.Final]
>         at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381) ~[netty-transport-4.1.69.Final.jar!/:4.1.69.Final]
>         at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370) ~[netty-transport-4.1.69.Final.jar!/:4.1.69.Final]
>         at org.opendaylight.netconf.nettyutil.ReconnectPromise.lambda$lockedConnect$0(ReconnectPromise.java:114) ~[netconf-netty-util-2.0.9.jar!/:na]
>         at org.opendaylight.netconf.nettyutil.AbstractNetconfDispatcher$3.initChannel(AbstractNetconfDispatcher.java:202) ~[netconf-netty-util-2.0.9.jar!/:na]
>         at org.opendaylight.netconf.nettyutil.AbstractNetconfDispatcher$3.initChannel(AbstractNetconfDispatcher.java:199) ~[netconf-netty-util-2.0.9.jar!/:na]
> 2024-03-14 15:40:01.898  WARN 136285 --- [ntLoopGroup-3-8] io.netty.bootstrap.Bootstrap             : Unknown channel option 'SO_BACKLOG' for channel '[id: 0x8e1e6ecb]'
> 2024-03-14 15:40:01.899  INFO 136285 --- [ntLoopGroup-7-8] io.netty.handler.logging.LoggingHandler  : [id: 0x8e1e6ecb] REGISTERED
> 2024-03-14 15:40:01.899  INFO 136285 --- [ntLoopGroup-7-8] io.netty.handler.logging.LoggingHandler  : [id: 0x8e1e6ecb] CONNECT: /127.0.0.1:17830
> 2024-03-14 15:40:01.900  INFO 136285 --- [ntLoopGroup-7-8] io.netty.handler.logging.LoggingHandler  : [id: 0x8e1e6ecb] CLOSE
> 2024-03-14 15:40:01.901  INFO 136285 --- [ntLoopGroup-7-8] io.netty.handler.logging.LoggingHandler  : [id: 0x8e1e6ecb] UNREGISTERED

Thank you for creating your report! We will get back to you, as soon as possible. Please note, that our support on GitHub is based on a non-guaranteed best effort. As soon as we are able, we will get back to you.
 
If you are in a hurry and have an inquiry regarding commercial support, please via this contact form: https://pantheon.tech/contact-us

**Comment by ihrasko** [comment]
Thanks, added to the developer queue.
