### ISSUE TITLE
Spring Boot Netconf example broken.

### ISSUE THREAD

**Issue by aronbergurj99** [PANTHEONtech/lighty#1916]
**Describe the bug**
2024-07-24T16:46:47.642Z ERROR 95816 --- [t-dispatcher-42] akka.actor.SupervisorStrategy            : Ask timed out on [Actor[akka://opendaylight-cluster-data/system/typedDdataReplicator#-62872494]] after [20000 ms]. Message of type [akka.cluster.ddata.typed.javadsl.Replicator$Update]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.

java.util.concurrent.TimeoutException: Ask timed out on [Actor[akka://opendaylight-cluster-data/system/typedDdataReplicator#-62872494]] after [20000 ms]. Message of type [akka.cluster.ddata.typed.javadsl.Replicator$Update]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
	at akka.actor.typed.scaladsl.AskPattern$.$anonfun$onTimeout$1(AskPattern.scala:131) ~[repackaged-akka-9.0.4.jar:na]
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:730) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:479) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222) ~[scala-library-2.13.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:365) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:314) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:318) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:270) ~[akka-actor_2.13-2.6.21.jar:2.6.21]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

**Branch**
lighty.io branch [eg. 20.x]

**To Reproduce**
1. unzip release 20.1.0 and cd into it
2. mvn clean install
3. cd lighty-examples/lighty-controller-springboot-netconf
4. mvn clean install
5. mvn spring-boot:run

**Expected behavior**
I would expect no errors in example.

Thank you for creating your report! We will get back to you, as soon as possible. Please note, that our support on GitHub is based on a non-guaranteed best effort. As soon as we are able, we will get back to you.
 
If you are in a hurry and have an inquiry regarding commercial support, please via this contact form: https://pantheon.tech/contact-us

**Comment by aronbergurj99** [comment]
This also happens in release 19 but not in 18.4

**Comment by ihrasko** [comment]
Hello,

currently we know about some `AskTimeoutException`s which occur during component initialization spotted in tests.

I assume this happens randomly - not all the time and thus is not blocking you, right?

Anyway, we are working towards fix this issue as soon possible.

**Comment by maurizio-lazzarini** [comment]
This morning I experiences the same exception on 20.1 and it is present each time the application is started.

**Comment by ihrasko** [comment]
Ok, I have the LOG message - but application is usable anyway.

You can run:
```
curl -i -X POST \
-c /tmp/lighty.cookies.txt \
-H "Content-Type:application/json" \
--data \
'{
    "username": "bob",
    "password": "secret"
}' \
"http://localhost:8888/services/security/login"
```

then

```
curl -i -b /tmp/lighty.cookies.txt \
-X GET "http://localhost:8888/services/data/topology/list"
```

all with success.

Best,
