### ISSUE TITLE
DOMNotification converted to Notification

### ISSUE THREAD

**Issue by SENCHONG** [PANTHEONtech/lighty#830]
Hello,
I want to convert the DOMNotification received from the device to Notification, but I encountered a problem.

```
import org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.lldp.rev210803.LldpNeighborStatusChange;

@Autowired
private MountPointService mountPointService;

@Autowired
private DOMMountPointService domMountPointService;

@Autowired
private BindingNormalizedNodeSerializer bindingNormalizedNodeSerializer;

private void test() {
    mountPointService.registerListener(NETCONF_TOPOLOGY_IID, new MountPointService.MountPointListener() {
        @Override
        public void onMountPointCreated(InstanceIdentifier<?> path) {
            YangInstanceIdentifier yangInstanceIdentifier = bindingNormalizedNodeSerializer.toYangInstanceIdentifier(path);
            DOMNotificationService domNotificationService = domMountPointService.getMountPoint(yangInstanceIdentifier).get().getService(DOMNotificationService.class).get();
            domNotificationService.registerNotificationListener(
                new DOMNotificationListener() {
                        @Override
                        public void onNotification(DOMNotification notification) {
                            Notification notification = bindingNormalizedNodeSerializer.fromNormalizedNodeNotification(domNotification.getType(), domNotification.getBody(), ((DOMEvent) domNotification).getEventInstant());
                        }
                    },
                SchemaNodeIdentifier.Absolute.of(InterfaceStatusChange.QNAME)
            );
        }

        @Override
        public void onMountPointRemoved(InstanceIdentifier<?> path) {

        }
    });
}
```

```
2021-09-29 16:05:27.624  WARN [sw-device-mgmr,,,] 34159 --- [ntLoopGroup-6-2] s.c.n.s.NetconfDeviceNotificationService : Listener com.test.sw.device.mgmr.notification.DOMNotificationListenerImpl@43d5a01f threw an uncaught exception during processing notification org.opendaylight.netconf.sal.connect.netconf.schema.mapping.NetconfMessageTransformer$NetconfDeviceNotification@39b802f3

java.lang.IllegalStateException: java.lang.NoSuchMethodException: org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.interfaces.rev201104.InterfaceStatusChange.bindingHashCode(org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.interfaces.rev201104.InterfaceStatusChange)
	at org.opendaylight.mdsal.binding.dom.codec.impl.ByteBuddyUtils.getMethod(ByteBuddyUtils.java:168)
	at org.opendaylight.mdsal.binding.dom.codec.impl.ByteBuddyUtils.describe(ByteBuddyUtils.java:84)
	at org.opendaylight.mdsal.binding.dom.codec.impl.ByteBuddyUtils.invokeMethod(ByteBuddyUtils.java:52)
	at org.opendaylight.mdsal.binding.dom.codec.impl.CodecDataObjectGenerator.codecHashCode(CodecDataObjectGenerator.java:313)
	at org.opendaylight.mdsal.binding.dom.codec.impl.CodecDataObjectGenerator.generateClass(CodecDataObjectGenerator.java:296)
	at org.opendaylight.mdsal.binding.dom.codec.loader.CodecClassLoader.doGenerateClass(CodecClassLoader.java:192)
	at org.opendaylight.mdsal.binding.dom.codec.loader.CodecClassLoader.generateClass(CodecClassLoader.java:146)
	at org.opendaylight.mdsal.binding.dom.codec.impl.CodecDataObjectGenerator.generateAugmentable(CodecDataObjectGenerator.java:268)
	at org.opendaylight.mdsal.binding.dom.codec.impl.DataObjectCodecContext.<init>(DataObjectCodecContext.java:155)
	at org.opendaylight.mdsal.binding.dom.codec.impl.DataObjectCodecContext.<init>(DataObjectCodecContext.java:94)
	at org.opendaylight.mdsal.binding.dom.codec.impl.NotificationCodecContext.<init>(NotificationCodecContext.java:73)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.createNotificationDataContext(SchemaRootCodecContext.java:258)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:62)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:58)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.getOrRethrow(SchemaRootCodecContext.java:321)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.streamChild(SchemaRootCodecContext.java:150)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.getNotification(SchemaRootCodecContext.java:174)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$6.load(SchemaRootCodecContext.java:126)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$6.load(SchemaRootCodecContext.java:117)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.getOrRethrow(SchemaRootCodecContext.java:321)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.getNotification(SchemaRootCodecContext.java:178)
	at org.opendaylight.mdsal.binding.dom.codec.impl.BindingCodecContext.getNotificationContext(BindingCodecContext.java:335)
	at org.opendaylight.mdsal.binding.dom.codec.impl.BindingCodecContext.fromNormalizedNodeNotification(BindingCodecContext.java:553)
	at org.opendaylight.mdsal.binding.dom.codec.spi.ForwardingBindingDOMCodecServices.fromNormalizedNodeNotification(ForwardingBindingDOMCodecServices.java:105)
	at com.test.sw.device.mgmr.notification.DOMNotificationListenerImpl.onNotification(DOMNotificationListenerImpl.java:40)
	at org.opendaylight.netconf.sal.connect.netconf.sal.NetconfDeviceNotificationService.publishNotification(NetconfDeviceNotificationService.java:35)
	at org.opendaylight.netconf.sal.connect.netconf.sal.NetconfDeviceSalProvider$MountInstance.publish(NetconfDeviceSalProvider.java:175)
	at org.opendaylight.netconf.sal.connect.netconf.sal.NetconfDeviceSalFacade.onNotification(NetconfDeviceSalFacade.java:71)
	at org.opendaylight.netconf.sal.connect.netconf.NotificationHandler.passNotification(NotificationHandler.java:90)
	at org.opendaylight.netconf.sal.connect.netconf.NotificationHandler.handleNotification(NotificationHandler.java:48)
	at org.opendaylight.netconf.sal.connect.netconf.NetconfDevice.onNotification(NetconfDevice.java:368)
	at org.opendaylight.netconf.sal.connect.netconf.NetconfDevice.onNotification(NetconfDevice.java:88)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.processNotification(NetconfDeviceCommunicator.java:405)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.onMessage(NetconfDeviceCommunicator.java:267)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.onMessage(NetconfDeviceCommunicator.java:48)
	at org.opendaylight.netconf.nettyutil.AbstractNetconfSession.handleMessage(AbstractNetconfSession.java:64)
	at org.opendaylight.netconf.nettyutil.AbstractNetconfSession.channelRead0(AbstractNetconfSession.java:187)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.interfaces.rev201104.InterfaceStatusChange.bindingHashCode(org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.interfaces.rev201104.InterfaceStatusChange)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.opendaylight.mdsal.binding.dom.codec.impl.ByteBuddyUtils.getMethod(ByteBuddyUtils.java:166)
	... 74 common frames omitted
```

I don’t know if it’s caused by improper configuration. Can you help me and solve this problem? Thank you very much!

**Comment by SENCHONG** [comment]
**Supplement**

*This problem occurred in version 14.2.x of lighty, but it was normal in version 13.0.0.*

**Comment by PeterSuna** [comment]
Hello SENCHONG,
inside provided exception log its looks like the issue is with your YANG model. Can you please check correct usage of node 'InterfaceStatusChange' inside model org.opendaylight.yang.gen.v1.urn.test.params.xml.ns.yang.test.interfaces.rev201104?
        
I tried to replicate converting DOMNotification to Notification, and It doesn't throw any exception. I used [Toaster](https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/master/examples/devices/lighty-toaster-device) device from lighty-netconf-simulator.
        
``` java		
        BindingNormalizedNodeSerializer bindingNormalizedNodeSerializer
                = lighty.getServices().getBindingNormalizedNodeSerializer();

        DOMNotificationService domNotificationService
                = getDOMMountPointToaster().getService(DOMNotificationService.class).get();
        ListenerRegistration<DOMNotificationListener> domNotificationListenerListenerRegistration
                = domNotificationService.registerNotificationListener(
                        new DOMNotificationListener() {
                            @Override
                            public void onNotification(DOMNotification domNotification) {
                                Notification notification = bindingNormalizedNodeSerializer.fromNormalizedNodeNotification(
                                        domNotification.getType(), domNotification.getBody(),
                                        ((DOMEvent) domNotification).getEventInstant());
                            }
                        },
                        Absolute.of(Toaster.QNAME)
        );
```        
I hope this helps.
