### ISSUE TITLE
lighty does not work after time consuming task running

### ISSUE THREAD

**Issue by marchest** [PANTHEONtech/lighty#898]
We are calling an endpoint on lighty which triggers time consuming job ( up to 2 mins ) behind the confd we are getting following rpc failure error after 60 seconds. And never working again. If we try to call any endpoint we see **Mount point does not exist error.** After restarting lighty everything works as expected.

```
 INFO [nioEventLoopGroup-9-3] (AbstractInternalLogger.java:148) - [id: 0x7a5bd6f2, L:/172.20.0.9:55834 - R:host.docker.internal/172.17.0.1:2022] FLUSH
2022-01-26T05:41:39.176110517Z  WARN [default-scheduled-pool-6-1] (KeepaliveSalFacade.java:305) - RemoteDevice{4}: Rpc failure detected. Reconnecting netconf session
2022-01-26T05:41:39.176148296Z java.util.concurrent.CancellationException: Task was cancelled.
2022-01-26T05:41:39.176165651Z 	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1425)
2022-01-26T05:41:39.176169697Z 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
2022-01-26T05:41:39.176172772Z 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
2022-01-26T05:41:39.176175825Z 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
2022-01-26T05:41:39.176179024Z 	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
2022-01-26T05:41:39.176182079Z 	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1122)
2022-01-26T05:41:39.176185091Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1072)
2022-01-26T05:41:39.176188316Z 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
2022-01-26T05:41:39.176191419Z 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
2022-01-26T05:41:39.176194539Z 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
2022-01-26T05:41:39.176197681Z 	at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:628)
2022-01-26T05:41:39.176200810Z 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:132)
2022-01-26T05:41:39.176204010Z 	at org.opendaylight.netconf.sal.connect.netconf.sal.KeepaliveSalFacade$RequestTimeoutTask.run(KeepaliveSalFacade.java:288)
2022-01-26T05:41:39.176207164Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2022-01-26T05:41:39.176271066Z 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2022-01-26T05:41:39.176276578Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2022-01-26T05:41:39.176279904Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2022-01-26T05:41:39.176283020Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2022-01-26T05:41:39.176286039Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-01-26T05:41:39.176289055Z 	at java.base/java.lang.Thread.run(Unknown Source)
2022-01-26T05:41:39.177998003Z  INFO [default-scheduled-pool-6-1] (KeepaliveSalFacade.java:110) - RemoteDevice{4}: Reconnecting inactive netconf session
2022-01-26T05:41:39.178175036Z  WARN [default-scheduled-pool-6-1] (NetconfDeviceCommunicator.java:259) - RemoteDevice{4}: Session terminated Session closed
```

**Branch**
lighty.io branch >>15.1

**To Reproduce**
1. Call an endpoint which takes up to 2 mins
2. You will get the rpc failure error.
3. Doesn't work until lighty restart

**Expected behavior**
In every circumstances lighty should response, even if crashes because of the previous requests

**Environment (please complete the following information):**
 - OS: "Ubuntu 20.04.3 LTS (Focal Fossa)"
 - Java Version =openjdk 11.0.13
 - Maven version=Apache Maven 3.6.3

Thanks in advance.

**Comment by PeterSuna** [comment]
Hello marchest, 
  from provided logs, it looks like your device is not responding to keep-allive messages. This can be caused
  by setting low [keepalive-delay](https://github.com/opendaylight/netconf/blob/master/netconf/sal-netconf-connector/src/main/yang/netconf-node-topology.yang#L192) property while you are connecting device. I have tried time-consuming jobs with 
  lighty and light-netconf-simulator. I have set keepalive-delay to 10 second and I have got same logs as you provide, but
  lighty-netconf-simulator was able to reconnect and works normally.
   ```
   WARN [default-scheduled-pool-6-2] (KeepaliveSalFacade.java:305) - RemoteDevice{new-netconf-device}: Rpc failure detected. Reconnecting netconf session
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1425)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
    ....
 INFO [default-scheduled-pool-6-2] (KeepaliveSalFacade.java:110) - RemoteDevice{new-netconf-device}: Reconnecting inactive netconf session
 WARN [default-scheduled-pool-6-2] (NetconfDeviceCommunicator.java:259) - RemoteDevice{new-netconf-device}: Session terminated Session closed
 WARN [nioEventLoopGroup-3-7] (ChannelInitializer.java:97) - Failed to initialize a channel. Closing: [id: 0xb7848baf]
io.netty.channel.ChannelPipelineException: org.opendaylight.netconf.nettyutil.ReconnectPromise$1 is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202)
    ....
 WARN [sshd-NetconfSshClient[6b3e6818]-nio2-thread-4] (StaticServerKeyVerifier.java:59) - Server at /127.0.0.1:17830 presented unverified RSA key: SHA256:OdrT1Z++jAjRW2eOfap3jU1Svyyw201ZeqSL2O4zjM4
 INFO [default-pool-5-1] (NetconfDevice.java:267) - RemoteDevice{new-netconf-device}: Netconf connector initialized successfully
 ```
 Can you please try to extend `keepalive-delay` or if you want you can disable keep-allive messages with set it to 0.
 ```bash
 curl --location --request PUT 'http://{{LIGHTY_IP}}:{{LIGHTY_PORT}}/restconf/data/network-topology:network-topology/topology=topology-netconf/node={{DEVICE_NAME}}' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "netconf-topology:node": [
        {
            "node-id": [{{DEVICE_NAME}},
            "host": {{DEVICE_IP}},
            "port":{{DEVICE_PORT}},
            "keepalive-delay": 180
        }
    ]
}'
```

I hope this helps.

**Comment by marchest** [comment]
Hi @PeterSuna 

Thank you for the kind response. I did exactly what you said. Please see below image.

![image](https://user-images.githubusercontent.com/13980801/154255038-86b0c3ad-5e95-4dae-abe2-e828193a5868.png)

After setting keepalive-delay to zero like you said **no **Lighty.io** restart** needed after time consuming job. Thanks for that.

But now I am getting application time out error after exactly 120 seconds later while my time-consuming job continues. Although setting default request time out 300 seconds. Please see the below error which is occured after 120 secs later. 

### How to increase this time out duration?


```
WARN [nioEventLoopGroup-3-12] (NetconfDeviceCommunicator.java:344) - RemoteDevice{53}: Error reply from remote device, request: <rpc message-id="m-83" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <TimeConsumingJobRequest xmlns="http://netconf-server.myorg.com/ns/dhcpd-kea-operations">
     
    </TimeConsumingJobRequest>
</rpc>
, response: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-83">
    <rpc-error>
        
        <error-type>application</error-type>
        
        <error-tag>operation-failed</error-tag>
        
        <error-severity>error</error-severity>
        
     <error-path xmlns:dhcpd-kea-operations="http://netconf-server.myorg.com/ns/dhcpd-kea-operations" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    
  </error-path>
    ################ ################ 
<error-message xml:lang="en">application timeout</error-message> 
        <error-info>
            <bad-element>host-specific-file-op</bad-element>
           
        </error-info>
        
    </rpc-error>
    
</rpc-reply>

NetconfDocumentedException{message=application timeout, errorType=APPLICATION, errorTag=operation-failed, errorSeverity=ERROR, errorInfo={bad-element=host-specific-file-op}}
	at org.opendaylight.netconf.api.NetconfDocumentedException.fromXMLDocument(NetconfDocumentedException.java:55)
	at org.opendaylight.netconf.sal.connect.netconf.util.NetconfMessageTransformUtil.checkSuccessReply(NetconfMessageTransformUtil.java:300)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.processMessage(NetconfDeviceCommunicator.java:342)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.onMessage(NetconfDeviceCommunicator.java:283)
	at org.opendaylight.netconf.sal.connect.netconf.listener.NetconfDeviceCommunicator.onMessage(NetconfDeviceCommunicator.java:50)
	at org.opendaylight.netconf.nettyutil.AbstractNetconfSession.handleMessage(AbstractNetconfSession.java:65)
	at org.opendaylight.netconf.nettyutil.AbstractNetconfSession.channelRead0(AbstractNetconfSession.java:186)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)




```


Thanks in advance

**Comment by marchest** [comment]
Hi @PeterSuna,

Please see the below message, and at the beginning of the stack trace there is a mentioning about time out error.
Bad element is generic error. I only get this error after long running situations.

```
<error-message xml:lang="en">***application timeout***</error-message>
        <error-info>
            <bad-element>host-specific-file-op</bad-element>
           
        </error-info>
        
    </rpc-error>
```

`NetconfDocumentedException{message=application timeout, errorType=APPLICATION, errorTag=operation-failed, errorSeverity=ERROR, errorInfo={bad-element=host-specific-file-op}}`

I am completely ensure that my request is valid. 

Is **default-request-timeout-millis** config being used between lighty.io to netconf server right?

Thanks.

**Comment by PeterSuna** [comment]
Hi marchest,
I apologize I did not notice this part. Yes you are correct [default-request-timeout-millis](https://github.com/opendaylight/netconf/blob/master/netconf/sal-netconf-connector/src/main/yang/netconf-node-topology.yang#L162) increase timeout in ODL.

However, received response is from device, hence I recommend to increase time-out inside your device. In the first message, you mentioned that you are using confd device. This device have set time-out for reply to 120s, if I'm not mistaken.
https://discuss.tail-f.com/t/how-to-increase-time-out-for-one-specific-command/1019/2

Best regards

**Comment by marchest** [comment]
Hi @PeterSuna,

Thank you very much, after increasing time-out on confd its done succesfully.

```

 <capi>
    <queryTimeout>PT180S</queryTimeout>
  </capi>
```

Kind Regards.
